before:
  hooks:
    - go mod tidy
gomod:
  proxy: true
builds:
- goarch:
    - amd64
    - arm64
  goos:
    - linux
  env:
    - CGO_ENABLED=0
checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'
archives:
- name_template: '{{ .Binary }}_{{ .Os }}_{{ .Arch }}'
  files:
  - '_examples/*'
  - '*.md'
dockers:
  - image_templates:
      - 'pasientskyhosting/domain_exporter:{{ .Tag }}-amd64'
      - 'pasientskyhosting/domain_exporter:{{ .Tag }}-amd64'
    dockerfile: Dockerfile
    use_buildx: true
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source=https://github.com/pasientskyhosting/domain_exporter"
      - "--platform=linux/amd64"
  - image_templates:
      - 'pasientskyhosting/domain_exporter:{{ .Tag }}-arm64v8'
      - 'pasientskyhosting/domain_exporter:{{ .Tag }}-arm64v8'
    dockerfile: Dockerfile
    use_buildx: true
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source=https://github.com/pasientskyhosting/domain_exporter"
      - "--platform=linux/arm64/v8"
    goarch: arm64
docker_manifests:
  - name_template: 'pasientskyhosting/domain_exporter:{{ .Tag }}'
    image_templates:
      - 'pasientskyhosting/domain_exporter:{{ .Tag }}-amd64'
      - 'pasientskyhosting/domain_exporter:{{ .Tag }}-arm64v8'
  - name_template: 'pasientskyhosting/domain_exporter:{{ .Tag }}'
    image_templates:
      - 'pasientskyhosting/domain_exporter:{{ .Tag }}-amd64'
      - 'pasientskyhosting/domain_exporter:{{ .Tag }}-arm64v8'
  - name_template: 'pasientskyhosting/domain_exporter:latest'
    image_templates:
      - 'pasientskyhosting/domain_exporter:{{ .Tag }}-amd64'
      - 'pasientskyhosting/domain_exporter:{{ .Tag }}-arm64v8'
  - name_template: 'pasientskyhosting/domain_exporter:latest'
    image_templates:
      - 'pasientskyhosting/domain_exporter:{{ .Tag }}-amd64'
      - 'pasientskyhosting/domain_exporter:{{ .Tag }}-arm64v8'
nfpms:
  - file_name_template: '{{ .ProjectName }}_{{ .Arch }}'
    homepage:  https://github.com/pasientskyhosting/domain_exporter
    description: Exports the expiration time of your domains as prometheus metrics.
    maintainer: Chad Jones <cj@patientsky.com>
    license: MIT
    vendor: Chad Jones
    formats:
      - apk
      - deb
      - rpm
